### ISSUE TITLE
[Feature Request] Disable Glances?

### ISSUE THREAD

**Issue by LeeThompson** [erohtar/Dasherr#1]
I don't run Glances, is there a way to disable the widget?

UPDATE: I ended up installing Glances and it seems handy although I still think the dashboard should be able to disable it.

**Comment by erohtar** [comment]
For sure - TBH it was on my short term goals to disable Glances (as I initially mentioned in my post in the sub) but since no one else asked, I figured maybe it's not a bad idea to keep it there for now. I'll try to include its removal in next update - thank you for the push.

**Comment by erohtar** [comment]
Done in v1.1.1 / Let me know if something doesn't work as intended
