### ISSUE TITLE
v1.04.01 included settings.json

### ISSUE THREAD

**Issue by soulruins** [erohtar/Dasherr#14]
Release [v1.04.01](https://github.com/erohtar/Dasherr/releases/tag/v1.04.01) included settings.json file. After updating we get a clean installation (((

**Comment by erohtar** [comment]
Oh man, I'm so sorry about that - I just fixed it. It was a bugfix update and in my rush to push it out quickly, I missed it. 
Apologies!

**Comment by soulruins** [comment]
No problem, checked the backup at the same time. :-) Thanks for the Dasherr!
