### ISSUE TITLE
[Bug] Font Awesome and Text Alignment

### ISSUE THREAD

**Issue by LeeThompson** [erohtar/Dasherr#17]
NOTE: This is pretty low priority.

Some font awesome icons appear to be wider than others causing text not to align as shown below:

![alignment](https://user-images.githubusercontent.com/1982261/206794283-1e46626a-e5d3-4696-9b72-18fd64c79371.jpg)

In this example, the icons are (from top to bottom):

```
"fa-brands fa-intercom"
"fa-solid fa-gamepad"
"fa-brands fa-windows"
```

Not sure how the fix would go except maybe add css padding for the text?

----
UPDATE: There are apparently some css settings you can do to resize fa icons although this may require the kit configuration. 
(ref: https://fontawesome.com/docs/web/style/fixed-width)

**Comment by erohtar** [comment]
I'd just been working on it and created a CSS solution before seeing your edit lol
But I think that's the better/standard approach - I'll undo my changes and try it now. 
Thanks for your inputs, I'll fix this in next update.

**Comment by erohtar** [comment]
Fixed in latest release, your updated input is the option I eventually went with - thank you
