### ISSUE TITLE
[Feature Request] Flexible Web Font Icon Support (FontAwesome etc)

### ISSUE THREAD

**Issue by LeeThompson** [erohtar/Dasherr#18]
Currently, Dasherr uses this line in `index.php`:
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">`

If a user wants to use a different set of web font icons, FontAwesome Pro, FontAwesome Kits (or self hosting) they are somewhat out of luck without modifying Dasherr to use a different stylesheet.

Somewhere (probably not in settings.json because it needs to be handled in index.php), you should be able to specify what to use for font icons.   Unfortunately it's not simply a one line substitution:

FontAwesome kits don't use a .css but use a .js script: 
`<script src="https://kit.fontawesome.com/(ID).js" crossorigin="anonymous"></script>`
(ref: https://fontawesome.com/docs/web/setup/use-kit)

FontAwesome's self hosting option seems to require more than one css entry:
```
  <link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet">
  <link href="/your-path-to-fontawesome/css/brands.css" rel="stylesheet">
  <link href="/your-path-to-fontawesome/css/solid.css" rel="stylesheet">
```
(ref: https://fontawesome.com/docs/web/setup/host-yourself/webfonts)

----
**NOTES:**

I edited index.php to use my FontAwesome kit by commenting out the css line and adding the kit's script src line and it appears to work.

Since this isn't something people are going to modify a lot, maybe this section could just be a php include to something like `custom.css`  to allow users to change web font icon stuff as needed?

In `index.php`:
_Replace_
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">`

_With_
`<?php include 'include/fonticons.php';?>`

**include/fonticons.php**
```
<?php
?> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
<?php
?>
```

This would allow users to be able to do whatever they need to add or change to support their icon platform/configuration.  
Since it's in PHP context, if they need to do any extra code work, that is available as well.

**Comment by erohtar** [comment]
Probably a dumb question, but what do FA kits do? 
Do they just carry a small subset of FA icons or do more than that?
If the former is the case, they'll only reduce load time for Dasherr on first time you load the page (or next time you load the page NOT from browser cache).

**Comment by LeeThompson** [comment]
I'm not super familiar with them, but it looks like they can be the same, a subset or a superset (with custom icons added).

----
**Update:**
I ended up doing FontAwesome Pro.

Kit capabilities:
* Two modes, font and SVG (it's transparent to the app including Dasherr).   If SVG mode only the icons being used are included.
* A kit can be exactly the same as what you have in the CSS
* They can also be subsets and supersets.
* They can also include custom icons (which need to be uploaded as SVG and FontAwesome's site is *extremely* picky about them.)

(You can have a kit without Pro but you have very limited options.)

I have Dasherr currently working with my FA kit (including some custom icons) with the above code changes.

**Comment by erohtar** [comment]
I have been going through your solution since yesterday (in my head and in code), but I keep running into these issue:
- If I include `fonticons.php` in future releases then it'll overwrite your custom settings, and if I don't include it then it'll obviously be a problem
- I do want to support more icons, but I want it to be more future proof, in a way that goes in line with your other request to support more icon sources; not just FA kits for now and when I add more sources then it all looks like an unplanned mess
- I don't want to create another dynamic file like `settings.json` as I already once accidentally included it in the release and someone's settings got overwritten - and creating more opportunities for me to f-up like that isn't the best plan

Pls give it a thought - I'm open to ideas on how this could be best implemented.

Happy Holidays

**Comment by LeeThompson** [comment]
That's a problem and I'll give it some thought.

Off the top of my head:

Have a `usericons.php` that has customized stuff, do a `file_exists`, if it's there, load it with a `require_once`, otherwise do the default stuff.

**Comment by LeeThompson** [comment]
I'm going to use this comment to brainstorm on, at the moment these are just ideas that I haven't worked out in any detail.

- Abstract icons.  On the backend they could be font awesome, png's, svg's or really anything else.    Problem with this is something would need to build the array/table to track them and something else would need to parse it from some kind of markup in the json.     Maybe stored as a separate json (although really, most stored data formats are a pain to edit for various reasons).

**Comment by erohtar** [comment]
I may have painted myself into a corner by hard-coding support for FA icons initially. Though that was totally because I originally made the app for personal use (making it public was a later decision once I felt there may be others who may need something like this).
But anyway, I digress - maybe the way forward is to support more icon types dynamically in the background somehow. 

Question - Is there a need to support more than one icon source at any time? Like some icons may be FA, some direct image links, some another web library etc? I don't mind supporting direct image links alongside any supported library but loading multiple libraries at once seems like overkill - what do you think?

**Comment by LeeThompson** [comment]
That's a good question, and no matter what you or I think, someone is going to have a use case that wants to use multiple sources.

### One icon source

If you really want to have only one icon source, I would go with image links for the following reasons:
- To have custom icons with FA, requires an annual subscription that is $99/year.    I don't know about other webfont icon sources.  (They are also a pain in the (bleep) to add.  They have to be SVG files and it is extremely picky about them.   I usually had to run icons through 3 _different_ tools to get them to work.  When rejected, the error messages were extremely cryptic and FA's FAQ was useless.)
- If you want FA icons self hosted (and there are many reasons for this; having the icons work even if there's an internet outage or a FA service outage) I _believe_ you have to have a subscription (I may be wrong on this and the self hosting option may then just be very limited).
- FA's (and probably other font icon resources) have glaring omissions for brands and services, requiring a lot of time to look around.
- Local icon sources mean they will be always there and what the user wants.

### Local Icons

Personally, this is always my preference.   I like to keep my intranet stuff from going out over the net as much as I can.

Probably would want a new `icon` folder, barring that use `res`.

The `settings.json` for icons could have something like:
`"Icon": "docker"` and Dasherr would then try `icon/docker.ico`
`"Icon": "docker.gif"` and Dasherr would then try `icon/docker.gif`
`"Icon": "/img/docker.png"` and Dasherr would use `img/docker.png`
(This idea doesn't preclude having more than one icon source.)

You could use css to keep image width and height in check.   (Although doing both you can mess up aspect ratios at the expense of neatness).

Now if the next question is acquiring icons, you could have an option or secondary tool that would download the favicons for the user, placing it in the `res` folder a  new `icon` folder.   Like a "`geticons.php`" script could go through the json files and do what it can to retrieve them.   Shouldn't be too difficult really, the biggest gotcha might be filename collision.

**Comment by erohtar** [comment]
Sorry about the delay - I've not been very happy with all the ways I tried implementing this so far. 

But I have added both features - support for custom headers and custom icons from local/web source. 
Here's an example of custom icons in use:
![image](https://user-images.githubusercontent.com/5120628/211141083-5f601c39-ddcc-4446-8061-7fa8401e4656.png)

While I like the implementation of custom icons, I'm still iffy on the whole custom headers part, and that's probably for the simple reason that this seems against the whole minimalist theme/ethos of the app. And once I open to non-free FA icons, adding support for other icon libraries could be expected too. And pls don't think I'm against giving people a choice, it's just that I wanted to keep the bells/whistles here to the bare minimum.

I'm adding here an unreleased beta for you, which also includes updated README. Pls try it out and let me know your thoughts on it all.
[dasherr.1.05.00-beta.zip](https://github.com/erohtar/Dasherr/files/10365800/dasherr.1.05.00-beta.zip)

Edit - Example usage of image icons in `settings.json`
```
		{
			"name": "Media",
			"tiles": [
				{
					"name": "JellyFin",
					"url": "http://homeserver:8096/",
					"icon": "icons/jellyfin.png"
				},
				{
					"name": "Radarr",
					"url": "http://homeserver:7878/",
					"icon": "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radarr.png"
				},
				{
					"name": "Sonarr",
					"url": "http://homeserver:8989/",
					"icon": "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/sonarr.png"
				}
			]
		}
```

**Comment by LeeThompson** [comment]
I apologize for the late reply, I'll try to test this today.

**Comment by LeeThompson** [comment]
Seems to work although I've only set icons for a few things so far.
Image alignment with the text is a problem, as usual, but that's fixable by editing the icons.

I'm going to setup more icons today and see how it goes.

**Comment by erohtar** [comment]
> Image alignment with the text is a problem
For image icons? I thought they looked okay from my limited testing..? They even look okay in my screenshot above.

> I'm going to setup more icons today and see how it goes.
Ok sure, thank you.

**Comment by LeeThompson** [comment]
> > Image alignment with the text is a problem
> > For image icons? I thought they looked okay from my limited testing..? They even look okay in my screenshot above.

It's an extremely minor nit, basically the icon for Gitea and Redmine are slightly below the text.  Not a big deal at all.

**Comment by LeeThompson** [comment]
This seems to be working well although it's probably worth noting that users will be better off not having huge icon files (don't really need a 1024x1024 icon image if it's just going to display at 32x32 or so) so the browser can load them faster.

Go ahead and close this unless you want to do more stuff.

**Comment by erohtar** [comment]
> basically the icon for Gitea and Redmine are slightly below the text

Maybe those icons aren't square?

> This seems to be working well although it's probably worth noting that users will be better off not having huge icon files (don't really need a 1024x1024 icon image if it's just going to display at 32x32 or so) so the browser can load them faster.

Of course. Though I'm sure some people would simply link to the web urls for ease of use.
