### ISSUE TITLE
[Feature Request] Multiple Glances

### ISSUE THREAD

**Issue by LeeThompson** [erohtar/Dasherr#2]
I have 3 Synology RAID arrays, what if I want to run glances on all 3?  (There's certainly room in the area of the widget to have multiple servers)

**Comment by erohtar** [comment]
Remove it or add More of it - make up your mind! lol jk 
So, how does that work (since I don't have something like that to test it on) - those multiple instances run on separate URLs?
Would you also need a name/title field for each instance?

**Comment by LeeThompson** [comment]
It would be best to be able to have a title above each instance, but yes something like:

```
"widgets": {
   "glances": {
       "name": "server1",
       "url": "http://server1:61208/",
       "refreshMs": 5000
   },
   "glances": {
       "name": "server2",
       "url": "http://server2:61208/",
       "refreshMs": 5000
   }
},

```

**Comment by erohtar** [comment]
I see. Though would it make more sense to have more 'pages' under Dasherr (each representing a separate instance in your case) instead of repeating same widget multiple times?

**Comment by LeeThompson** [comment]
That would be one way to do it, the other though is the current Dasherr widget design is wasting an incredible amount of space. (3 rows with huge right blank space).

If it ends up as one widget per page maybe have it be expressed in columns instead of rows, I would also like to have a name: option so I know which machine I'm looking at.

Here is a mockup showing both a horizontal layout and multiple instances.

![mockup](https://user-images.githubusercontent.com/1982261/201493255-6d2019fd-642c-4f65-81d6-0f20f5ab401d.jpg)

Might be better with a little less spacing between the icon and the value as well.

**Comment by erohtar** [comment]
I fully agree with you on the 'wasted' space, even though to me personally the clean look of it hasn't lost its appeal.
But one major reason to keep the Glances values vertical (even though I did try horizontal a few times, very much like your screenshot) was that maybe in future I might decide to add support for another widget or two, and they'd fit better in this format.

But tbh I'm liking your mockup too (with the spacing corrected of course). Though right now the bigger change would be to add support for multiple instances of the same widget - something which didn't even occur to me as a possible need till you brought it up.

**Comment by LeeThompson** [comment]
Well we all develop stuff based on what we have around us, I have 3 Synology boxes (and docker hosts) and several Windows boxes (2 Windows Server).   (I know, I need help. :) )    So for my administrative dashboard, I would ideally like to see the status of the 3 Synology's at a (forgive the pun) Glance.

**Comment by erohtar** [comment]
Point well taken - I'll raise priority of this request.

Btw maybe you can suggest something here - once I implement support of multiple Glances, it'd not work like the code here
```
"widgets": {
   "glances": {
       "name": "server1",
       "url": "http://server1:61208/",
       "refreshMs": 5000
   },
   "glances": {
       "name": "server2",
       "url": "http://server2:61208/",
       "refreshMs": 5000
   }
},
```
In here the two named glances entries are at same level - instead it'd be an array where items would be read in order (the same way currently Sections and Tiles are arrays. 
Now my concern is that making that change would break existing settings files from versions so far.

**Comment by LeeThompson** [comment]
That's fine, that was just an example.
It'll need to be an array anyway to process it.

**Comment by LeeThompson** [comment]
Unfortunately, I am _far_ from an expert in JSON.

One method (I have no idea if this is doable):

Under page add support for the widget array, if that isn't present then the current widget section could be read.  (And if the widget array is present for the page, then the old style widget section would ignored.)

**Comment by erohtar** [comment]
Huh. I think that should work! 
I will of course need to create some sort of internal id structure for the code to be able to identify each widget instance with a new type of unique id system because 'widgetGlances' won't work anymore, but I suppose that should not be much of a problem.

**Comment by erohtar** [comment]
I found this enhancement to be useful to me too, so thank you for suggesting it.

Though in favor of keeping code simple and more future-facing, and also given how small the one time `settings.json` change would be for a user, I didn't try to implement a dynamic array check.
