### ISSUE TITLE
[Bug] Using Edit Function On Non-Standard Pages Save To Wrong File

### ISSUE THREAD

**Issue by LeeThompson** [erohtar/Dasherr#22]
If you use Dasherr's edit function on a non-standard page (anything not `settings.json`) when you click the save icon, the changes are written to `settings.json`.

(I would've caught this sooner but I usually use Notepad++ for editing.)

**Comment by erohtar** [comment]
So sorry for my long disappearance and for this (known) bug not being already fixed. I was under the impression that I'd pushed this one out already.
My apologies again.

**Comment by LeeThompson** [comment]
No worries.
