### ISSUE TITLE
[Feature Request] More Icon Choices

### ISSUE THREAD

**Issue by LeeThompson** [erohtar/Dasherr#3]
In addition to FontAwesome, it would be nice if **Dasherr** could support:

- Additional Web Font icon sources
- A custom icon folder (.ico, .gif and .png formats)

I've found FontAwesome "free" is actually quite limiting in icon selection (even with the Pro icons, it's still limited anyway).

**Comment by erohtar** [comment]
Yeah I figured sooner or later someone would ask for this, even though I personally felt staying within the FA choices went nicely with the whole minimal mindset with which I created Dasherr. But giving alternatives and more choices isn't a be a bad idea - I'll surely keep this one on the list.

**Comment by LeeThompson** [comment]
I'm with you on the minimalist design, it's my preference as well.

**Comment by erohtar** [comment]
So for now I'll mark it as a low priority, while still keeping an open mind about it and in case more users feel the same way, I'll certainly add it.

**Comment by LeeThompson** [comment]
This is low priority for me too really.   The icons are neat but I can also live without them.

One idea would be an option to use the URL's own shortcut icon (since the hosts are being "'pinged" anyway, although this might slow it down and you'd probably need to store them somewhere).     So maybe a "`useShortcutIcon`" boolean at (in order of precedence) page, section and tile level?

**Comment by erohtar** [comment]
By 'URL's own shortcut icon' if you mean reading each url's index page and grabbing their favicon and displaying that, then that sounds like a bad idea since page load performance would take a severe hit. One of the reasons I made (and use) Dasherr is that it's much lighter than some other dashboards I've used in past.

**Comment by LeeThompson** [comment]
Yeah that's what I was thinking too, that it would be too resource heavy (especially if you have a lot of entries), worsening if they aren't on the same subnet. 

But future support of png/gif/ico/svg icons + other "logo font" support would be great.

**Comment by erohtar** [comment]
> But future support of png/gif/ico/svg icons + other "logo font" support would be great.

I agree, and even more so if the user downloads these and puts them in their res/ folder
