### ISSUE TITLE
[Feature Request] openTab at Tile level

### ISSUE THREAD

**Issue by LeeThompson** [erohtar/Dasherr#5]
There is already options to `disable` and `disableCheck` but it would also be useful to be able to override `"openTab"`.

For instance, if I wanted to have additional `Dasherr` 'pages', I could have those tiles be set to `"openTab": "same"` giving it the appearance of a single dashboard.

**Comment by erohtar** [comment]
TBH having support for multiple 'pages' was one of the ideas when I initially started on it (that's the whole reason that section is called pages), but down the line that plan changed.
Could you maybe pls give me some actual use cases to help me envision and make a plan if I go ahead with it?

Also, just out of curiosity - if you don't mind, could you also pls share your Dasherr setup?
Thanks for all the inputs!

**Comment by erohtar** [comment]
Sorry I didn't address your main request - openTab at Tile level that overrides page setting - hmm, it's not a bad idea - though I got a feeling someone would want it to be a Section-wide setting too lol

**Comment by LeeThompson** [comment]
Yeah, should be available for each level I think, just as an option.

**Comment by LeeThompson** [comment]
As for the larger issue, I'm trying to replace my old manually created "jump page" (organized bookmarks really) with something  more modern, unfortunately I have a *lot* of them.

I'm attaching a partial screenshot of my jump page, I'm redacting bits that may reveal too much information about my location or identity.

The full jump page is 750 lines (including all HTML tags and formatting).

My initial thought was to just do it all in Dasherr but I don't think that would work so I was thinking if I could have multiple instances of it in folders I could have multiple pages if I had those links open in same tab.

![jumppage_sample](https://user-images.githubusercontent.com/1982261/201492649-9ef81e5b-8b91-4a64-a0de-cfcac5e5dc84.jpg)

(The centered text on the dark red background are aria search links which oddly I rarely remember to use.)

The items 'highlighted' in yellow are the `a href`'s, for the most part they all open in a new tab.

**Comment by LeeThompson** [comment]
My current dasherr configuration is mostly centered around my 3 Synology units and their docker containers and I'm already at more than one 'page' (as I need to scroll down).

**Comment by erohtar** [comment]
> Yeah, should be available for each level I think, just as an option.

Hmm, though I still feel your initial suggestion of an override being available just at per Tile level would be best (this is of course to be used as exceptions - norm would be whatever is set at top in page settings)

> I'm attaching a partial screenshot of my jump page, I'm redacting bits that may reveal too much information about my location or identity.

Of course.

> My initial thought was to just do it all in Dasherr but I don't think that would work so I was thinking if I could have multiple instances of it in folders I could have multiple pages if I had those links open in same tab.

Since Dasherr settings are all in a simple json file, I'd just write some script to read your jump page data and output json data that you could simply copy/paste in Dasherr settings - then you just delete any tiles that you don't need there - just a thought.

**Comment by LeeThompson** [comment]
A script to convert was part of the plan actually, I just need some way to have all this stuff in a manageable state so having certain links open in same on Dasherr would go a long way towards that.   I could have a 'top dasherr' page that just lists my old sections, that then opens the next section.

(One idea too would be to be able to pass a query string to Dasherr to read a different json file, although obviously great care 
must be taken on that route for security reasons.

something like: `index.php?use=settings2.json` maybe)

**Comment by erohtar** [comment]
Alright, I'll definitely try to put the per-tile openTab setting in the next update.

Also, your suggestion of passing an alternate settings file is actually quite intriguing - this definitely is a much cleaner way to implement a separate Dasherr instance without having to duplicate the entire set of files/folders. 

Though when I initially mentioned more Dasherr 'pages', I meant somehow implementing multiple instances of **this** part in same settings file:
![image](https://user-images.githubusercontent.com/5120628/201494127-af37b3ed-9191-4b48-9eb6-8a17f9400b25.png)
Idk, maybe like tabs - anything that'd not break the clean look of the current interface.

**Comment by LeeThompson** [comment]
Tabs would be cool too!

One concern though would be the host checks might start getting too slow unless there was a way to have it only check hosts in the 'active' tab.

Another concern is a really huge json file (and it's really easy to forget to leave off the last comma in a group of things. ;) )

**Comment by erohtar** [comment]
While you're right about checking hosts on other tabs affecting performance, it should not be too apparent because they're checked asynchronously and the command to check them would be issued in the order of the tabs itself - so the user would only see those online dots appear on the first tab, unless the moment the page loads they immediately go and click the very last tab!

And yea, I hate the commas in json lol

**Comment by erohtar** [comment]
Allowed openTab Page setting to be overridden at per-Tile level in v1.1.2
