### ISSUE TITLE
[Feature Request] password for dashboard

### ISSUE THREAD

**Issue by Sparklingx** [erohtar/Dasherr#7]
All ips having service open in a open port shows up in websites like shodan and other hack sites that keeps scaning ips around the world so it is  wise to have a password locked dashboard

**Comment by erohtar** [comment]
You're right - unless you're using Dasherr in a closed network/VPN, you need some sort of authentication built into it.
I'll add this as a mid-priority for now and start looking into options to implement it.
Thank you for bringing it up

**Comment by LeeThompson** [comment]
@Sparklingx In the meantime, you should be able to lock it down with your web server software as a workaround.

**Comment by erohtar** [comment]
Sorry I've taken a long while implementing this one. I did look into it though, and while considering possibilities, it occurred to me wouldn't a simpler implementation be to just use a [simple .htpasswd file](https://www.hostwinds.com/tutorials/create-use-htpasswd)?
This will add zero overhead for users who don't open the dashboard to outside world, and lock it down for users who do. Thoughts?

**Comment by 2IkHLHB** [comment]
> ...wouldn't a simpler implementation be to just use a [simple .htpasswd file](https://www.hostwinds.com/tutorials/create-use-htpasswd)? This will add zero overhead for users who don't open the dashboard to outside world, and lock it down for users who do. Thoughts?

I think this would be a great idea.

**Comment by Sparklingx** [comment]
agree
