### ISSUE TITLE
[Feature Request] Method(s) of having multiple Dasherr 'Pages'

### ISSUE THREAD

**Issue by LeeThompson** [erohtar/Dasherr#8]
(We discussed this in an (now closed) issue and I thought it would be a good idea to separate it.)

Due to the sheer amount of stuff I want to put on Dasherr having it all on one page is unrealistic.

There seem to be a few ways to do this:

> **Multiple Dasherr Instances** 

While this can work even now, one you have more than 2-3 it starts to get unmanageable and when they need to be updated it is even more problematic.

_I don't actually see this as a tenable solution._

> **Specify Alternate Setting File**

One idea would be to specify an alternate setting file on the query string, then you could set the tiles in the 'master' Dasherr instance to reload with another 'page' of options.

_Something like:_
`index.php?use=settings2.json`
`index.php?settings=settings2.json`

I think this would be the easiest method to implement.

> **Tabs**

Tabs within Dasherr itself would also be a solution, unfortunately it would likely break current configurations since you'd need to be able to have multiple pages defined (and each of those with it's own widgets, sections and tiles.)

**Conclusions**

I would like to see being able to load alternate settings, and I also think tabs may be interesting as well so I'd like to see both if possible.  (Please don't hit me.)

**Comment by erohtar** [comment]
Yes, good thing you brought it up separately here, and thank you for presenting the options we went over, so clearly.

I'm (heavily) leaning towards the alternate settings file option - it is the least destructive towards established structure, it seems to be (right now at least) quickest to implement, and best of all - it opens the multiple instances to be able to use entirely separate sets of top-level title/theme etc (something that won't be there with tabs), which would mean one could very easily tell from a glance, which page instance they're looking at. I love it.

**Comment by LeeThompson** [comment]
Yeah that's my favorite too.   If you do add tabs later, it could even just use the same method "under the hood".

**Comment by erohtar** [comment]
Added with latest release. And I must say I love how it turned out.
I was going to submit the release including an alt config with set of dummy sections/tiles, but at the last moment decided to actually put bookmarks to a few self-hosting resources instead, so that I'd use this feature myself (even though my set of self-hosted services fit on a single page).
![image](https://user-images.githubusercontent.com/5120628/203339746-2b41dfa6-65dd-4104-a7f3-d223f3ab5485.png)

I'll wait to hear your thoughts before closing this topic - thanks again for the ideas and push

**Comment by LeeThompson** [comment]
Seems to work well!

Thank you very much for adding this.

**Comment by erohtar** [comment]
I just realized - the editor is still hard-coded to edit the default settings file. Need to fix that.

**Comment by erohtar** [comment]
Should be good now with v1.03.01
