### ISSUE TITLE
[Question] FontAwesome Pro

### ISSUE THREAD

**Issue by LeeThompson** [erohtar/Dasherr#9]
This may be more of a support question because I can't find any specifics on FontAwesome's site so forgive me if I'm not understanding how it works.

If I wanted to use FontAwesome Pro icons and purchased the Pro plan, how could I then have Dasherr use the fonts?   Is there a way I could put an API key into Dasherr or is it tied to my IP address?

**Comment by erohtar** [comment]
Hmm.. I have no ready answer to this right now really. As I don't have a pro plan with them and so far no one besides you asked for it, I never looked into it. It's something I'll add to my list, albeit as a low priority right now.

**Comment by LeeThompson** [comment]
That's fine, it's a hypothetical situation to me too, their site is remarkably unclear how "pro" works.

**Comment by erohtar** [comment]
Oh glad to hear it's not just me who felt that way! I tried to quickly go through their docs to see how it works but nothing jumped at me. Oh well, maybe a better use of my time would be to add support for using any web/local images as icons, such as [these](https://thehomelab.wiki/books/helpful-tools-resources/page/icons-for-self-hosted-dashboards)

**Comment by LeeThompson** [comment]
Those are nice, I think also having a `"Icon":` with "`custom/icon.ico`" or `"/images/myicon.gif`" would go a long way too.

**Comment by erohtar** [comment]
>add support for using any web/local images as icons

Ah yes, that's what I meant by **local** here

**Comment by LeeThompson** [comment]
Ah well then, works for me!
